// sdk/mcp/tools.js — the MCP tool registry for MAAC Go Email.
//
// One registry, every surface:
//   - api/mcp.js                         Streamable HTTP at /api/mcp
//   - sdk/mcp/bin/maacgo-email-mcp.js    stdio, shipped as @maacgo/email-mcp
//   - .well-known/mcp/server-card.json   generated by sdk/mcp/scripts/build-server-card.mjs
//
// Every handler calls the public REST API with the caller's own API key, so
// scopes, quota, the wallet and the suppression list all apply exactly as they
// would to a direct fetch. There is no privileged path here.

export const SERVER_NAME = 'maacgo-email';
export const SERVER_TITLE = 'MAAC Go Email';
export const SERVER_VERSION = '0.3.0';
export const PUBLIC_SITE = 'https://edm.cresclab.com';
export const MCP_URL = PUBLIC_SITE + '/api/mcp';
export const DOCS_URL = PUBLIC_SITE + '/mcp';
// Oldest last. The server answers with the client's version when it is one of
// these, otherwise with the first.
export const PROTOCOL_VERSIONS = ['2025-06-18', '2025-03-26', '2024-11-05'];

const DEFAULT_BASE_URL = PUBLIC_SITE + '/api';

export function makeClient({ apiKey, baseUrl = DEFAULT_BASE_URL, fetch: fetchImpl = globalThis.fetch } = {}) {
  if (!apiKey) throw new Error('apiKey_required');
  const base = String(baseUrl || DEFAULT_BASE_URL).replace(/\/+$/, '');
  return async function call(method, path, body) {
    const r = await fetchImpl(base + path, {
      method,
      headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + apiKey },
      body: body ? JSON.stringify(body) : undefined,
    });
    const ct = r.headers.get('content-type') || '';
    const data = ct.includes('json') ? await r.json() : await r.text();
    if (!r.ok) {
      const err = new Error(data?.error || 'http_' + r.status);
      err.status = r.status;
      err.data = data;
      throw err;
    }
    return data;
  };
}

// ---- schema pieces ---------------------------------------------------------

const id = (what) => ({ type: 'string', pattern: '^[0-9]+$', description: what });
const NO_ARGS = { type: 'object', properties: {} };

const segment = (description, { allowNone = false } = {}) => ({
  type: 'object',
  description,
  properties: {
    type: {
      type: 'string',
      enum: [...(allowNone ? ['none'] : []), 'all', 'tag', 'engaged', 'never_engaged'],
      description: '"all" = every contact; "tag" = contacts carrying `tag`; "engaged" = ever opened or clicked; "never_engaged" = never opened or clicked' + (allowNone ? '; "none" = leave nobody out.' : '.'),
    },
    tag: { type: 'string', description: 'The tag, when type is "tag".' },
  },
  required: ['type'],
});

// MCP tool annotations. Hints only — the REST API enforces the real rules.
const READ = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false };
const write = (o = {}) => ({ readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false, ...o });

const toolError = (code) => Object.assign(new Error(code), { data: { error: code } });

// ---- the 22 tools ----------------------------------------------------------

export const TOOLS = [
  {
    name: 'send_email',
    title: 'Send email',
    description: 'Send one transactional email — a receipt, an OTP, an order update. Draws on the free monthly allowance first, then prepaid credit. Prefer template_id over inline html for anything sent more than once: the stored template is byte-identical every time and {{variables}} carry the per-message parts. IMPORTANT: a key beginning sk_test_ only RECORDS the message — nothing is delivered, even though the result says status "sent". Check test_mode in the result; get_me shows the key mode.',
    inputSchema: {
      type: 'object',
      properties: {
        to: { type: 'string', format: 'email', description: 'Recipient email address (one address).' },
        subject: { type: 'string', maxLength: 300, description: 'Subject line, up to 300 characters. Required unless template_id is given (then it overrides the template subject).' },
        html: { type: 'string', description: 'HTML body. Either html, text or template_id is required.' },
        text: { type: 'string', description: 'Plain-text body. Derived from html when omitted.' },
        template_id: { type: 'string', pattern: '^[0-9]+$', description: 'Id of a stored template (see list_templates / create_template). Supplies subject, html and text.' },
        variables: { type: 'object', description: 'Values for the template\'s {{variables}}, e.g. {"first_name":"Ada","order_id":"1042"}. A {{name|fallback}} without a value uses the fallback.', additionalProperties: { type: 'string' } },
        from: { type: 'string', description: 'Display name shown to the recipient. The address itself is the account\'s sending address.' },
        reply_to: { type: 'string', format: 'email', description: 'Where replies should go.' },
      },
      required: ['to'],
    },
    annotations: write({ openWorldHint: true }),
    requiredScopes: ['email.send'],
    handler: (call, a) => call('POST', '/email/send', a),
  },
  {
    name: 'list_templates',
    title: 'List templates',
    description: 'Stored transactional templates on this account (up to 100), with the {{variables}} each one expects. Use a template_id with send_email instead of inlining HTML every time.',
    inputSchema: NO_ARGS,
    annotations: READ,
    requiredScopes: ['email.read'],
    handler: (call) => call('GET', '/templates'),
  },
  {
    name: 'get_template',
    title: 'Get template',
    description: 'One stored template: name, subject, html, text and the variables it uses.',
    inputSchema: { type: 'object', properties: { id: id('Template id from list_templates.') }, required: ['id'] },
    annotations: READ,
    requiredScopes: ['email.read'],
    handler: (call, a) => call('GET', '/templates/' + encodeURIComponent(a.id)),
  },
  {
    name: 'create_template',
    title: 'Create template',
    description: 'Save a reusable transactional template. Write {{variable}} or {{variable|fallback}} anywhere in subject, html or text; pass the values as `variables` on send_email. Returns the id to send with. Names are unique per account; an account holds up to 100 templates.',
    inputSchema: {
      type: 'object',
      properties: {
        name: { type: 'string', minLength: 1, maxLength: 120, description: 'Short unique name, e.g. "order-confirmation".' },
        subject: { type: 'string', minLength: 1, maxLength: 300, description: 'Subject line; may use {{variables}}.' },
        html: { type: 'string', description: 'HTML body. Either html or text is required.' },
        text: { type: 'string', description: 'Plain-text body.' },
      },
      required: ['name', 'subject'],
    },
    annotations: write(),
    requiredScopes: ['email.send'],
    handler: (call, a) => call('POST', '/templates', a),
  },
  {
    name: 'update_template',
    title: 'Update template',
    description: 'Change the name, subject, html or text of a stored template. Only the fields you pass change.',
    inputSchema: {
      type: 'object',
      properties: {
        id: id('Template id from list_templates.'),
        name: { type: 'string', minLength: 1, maxLength: 120, description: 'New unique name.' },
        subject: { type: 'string', minLength: 1, maxLength: 300, description: 'New subject line.' },
        html: { type: 'string', description: 'New HTML body.' },
        text: { type: 'string', description: 'New plain-text body.' },
      },
      required: ['id'],
    },
    annotations: write({ idempotentHint: true }),
    requiredScopes: ['email.send'],
    handler: (call, { id: tid, ...rest }) => call('PATCH', '/templates/' + encodeURIComponent(tid), rest),
  },
  {
    name: 'delete_template',
    title: 'Delete template',
    description: 'Delete a stored template. This cannot be undone. Messages already sent with it are unaffected.',
    inputSchema: { type: 'object', properties: { id: id('Template id from list_templates.') }, required: ['id'] },
    annotations: write({ destructiveHint: true, idempotentHint: true }),
    requiredScopes: ['email.send'],
    handler: (call, a) => call('DELETE', '/templates/' + encodeURIComponent(a.id)),
  },
  {
    name: 'get_message',
    title: 'Get message',
    description: 'Look up one transactional message by id and see whether it was delivered, bounced or is still in flight.',
    inputSchema: { type: 'object', properties: { id: id('Message id returned by send_email or list_messages.') }, required: ['id'] },
    annotations: READ,
    requiredScopes: ['email.read'],
    handler: (call, a) => call('GET', '/email/' + encodeURIComponent(a.id)),
  },
  {
    name: 'list_messages',
    title: 'List messages',
    description: 'List the 100 most recent transactional messages with their delivery status.',
    inputSchema: NO_ARGS,
    annotations: READ,
    requiredScopes: ['email.read'],
    handler: (call) => call('GET', '/email'),
  },
  {
    name: 'list_campaigns',
    title: 'List campaigns',
    description: 'List the email campaigns on the account (newest 500) with their status; sent ones carry their delivery funnel, unsent ones the live audience count.',
    inputSchema: NO_ARGS,
    annotations: READ,
    requiredScopes: ['campaigns.read'],
    handler: (call) => call('GET', '/campaigns'),
  },
  {
    name: 'get_campaign',
    title: 'Get campaign',
    description: 'One campaign in full: name, subject, preview text, sender name, content blocks, audience, status, schedule, review state and web-version link. For delivery results use campaign_report.',
    inputSchema: { type: 'object', properties: { id: id('Campaign id from list_campaigns.') }, required: ['id'] },
    annotations: READ,
    requiredScopes: ['campaigns.read'],
    handler: (call, a) => call('GET', '/campaigns/' + encodeURIComponent(a.id)),
  },
  {
    name: 'campaign_report',
    title: 'Campaign report',
    description: 'Delivery report for one campaign: attempted, skipped, sent, bounced, delivered, opened, clicked, plus up to 1,000 per-recipient rows.',
    inputSchema: { type: 'object', properties: { id: id('Campaign id from list_campaigns.') }, required: ['id'] },
    annotations: READ,
    requiredScopes: ['campaigns.read'],
    handler: (call, a) => call('GET', '/campaigns/' + encodeURIComponent(a.id) + '/report'),
  },
  {
    name: 'estimate_campaign',
    title: 'Estimate campaign audience',
    description: 'How many contacts an audience would actually reach, after unsubscribes, bounces, exclusions and the limits on accounts without a verified domain. Nothing is sent or charged. Run this before send_campaign and tell the user the count.',
    inputSchema: {
      type: 'object',
      properties: {
        include: segment('Who to send to. Defaults to {"type":"all"}.'),
        exclude: segment('Who to leave out. Defaults to {"type":"none"}.', { allowNone: true }),
      },
    },
    annotations: READ,
    requiredScopes: ['campaigns.read'],
    handler: (call, a) => call('POST', '/campaigns/0/estimate', { audience: { include: a.include || { type: 'all' }, exclude: a.exclude || { type: 'none' } } }),
  },
  {
    name: 'send_campaign',
    title: 'Send campaign',
    description: 'Send an existing draft campaign to its saved audience now, or schedule it. Campaigns are written by a person in the editor; API keys cannot create or edit them. Refuses with a priced breakdown if the wallet cannot cover it — nothing is queued or charged in that case. A campaign can be sent only once. Needs a live key (sk_live_…): a test key is refused, because test keys never deliver.',
    inputSchema: {
      type: 'object',
      properties: {
        id: id('Campaign id from list_campaigns.'),
        scheduled_at: { type: 'integer', minimum: 0, description: 'Optional Unix epoch milliseconds to send at instead of now.' },
      },
      required: ['id'],
    },
    annotations: write({ openWorldHint: true }),
    requiredScopes: ['campaigns.send'],
    handler: (call, a) => call('POST', '/campaigns/' + encodeURIComponent(a.id) + '/send', a.scheduled_at ? { scheduled_at: a.scheduled_at } : {}),
  },
  {
    name: 'list_contacts',
    title: 'List contacts',
    description: 'The newest 2,000 contacts on the account with their ids, tags and sendability status, plus every tag in use. The ids are what tag_contacts and contact_activity take.',
    inputSchema: NO_ARGS,
    annotations: READ,
    requiredScopes: ['contacts.read'],
    handler: (call) => call('GET', '/contacts'),
  },
  {
    name: 'add_contact',
    title: 'Add contact',
    description: 'Add one contact, or update the first name of one already on the list. Only add people who have agreed to hear from this sender. Refused with contact_limit when the plan\'s contact allowance is full.',
    inputSchema: {
      type: 'object',
      properties: {
        email: { type: 'string', format: 'email', description: 'The contact\'s email address.' },
        first_name: { type: 'string', description: 'First name, used by {{first_name}} in campaigns.' },
        last_name: { type: 'string', description: 'Last name.' },
        tags: { type: 'array', items: { type: 'string' }, description: 'Tags for a new contact, e.g. ["vip"].' },
      },
      required: ['email'],
    },
    annotations: write({ idempotentHint: true }),
    requiredScopes: ['contacts.write'],
    handler: (call, a) => call('POST', '/contacts', a),
  },
  {
    name: 'import_contacts',
    title: 'Import contacts',
    description: 'Add up to 5,000 contacts in one call; rows past 5,000 are dropped and counted as `truncated`. Addresses already on the list and invalid addresses are skipped, not updated. If the new people would exceed the plan\'s contact allowance the whole call is refused with contact_limit and nothing is added. Only import people who agreed to hear from this sender. Until the account has a verified sending domain, credit or a paid plan, campaigns reach at most 50 of these contacts a day (200 in total); estimate_campaign shows the exact reach.',
    inputSchema: {
      type: 'object',
      properties: {
        rows: {
          type: 'array',
          minItems: 1,
          maxItems: 5000,
          description: 'The contacts to add.',
          items: {
            type: 'object',
            properties: {
              email: { type: 'string', format: 'email', description: 'Email address.' },
              first_name: { type: 'string', maxLength: 120, description: 'First name.' },
              last_name: { type: 'string', maxLength: 120, description: 'Last name.' },
              tags: { type: 'array', maxItems: 20, items: { type: 'string', maxLength: 40 }, description: 'Tags for this row (up to 20, 40 characters each, including `tag` below).' },
            },
            required: ['email'],
          },
        },
        tag: { type: 'string', maxLength: 40, description: 'One tag added to every row, e.g. "webinar-2026-10".' },
      },
      required: ['rows'],
    },
    annotations: write({ idempotentHint: true }),
    requiredScopes: ['contacts.write'],
    handler: (call, a) => call('POST', '/contacts/import', { rows: a.rows, ...(a.tag ? { tag: a.tag } : {}) }),
  },
  {
    name: 'tag_contacts',
    title: 'Tag or untag contacts',
    description: 'Add a tag to, or remove a tag from, many contacts at once, by the ids list_contacts returns. Contacts that already have (or already lack) the tag are left alone; `updated` counts the ones that changed. This tool never deletes contacts.',
    inputSchema: {
      type: 'object',
      properties: {
        op: { type: 'string', enum: ['tag', 'untag'], description: '"tag" adds the tag, "untag" removes it.' },
        ids: { type: 'array', minItems: 1, items: { type: 'string', pattern: '^[0-9]+$' }, description: 'Contact ids from list_contacts.' },
        tag: { type: 'string', minLength: 1, description: 'The tag, e.g. "vip".' },
      },
      required: ['op', 'ids', 'tag'],
    },
    annotations: write({ idempotentHint: true }),
    requiredScopes: ['contacts.write'],
    handler: async (call, a) => {
      // The REST endpoint also deletes; this tool must never reach that branch.
      if (a.op !== 'tag' && a.op !== 'untag') throw toolError('bad_op');
      return call('POST', '/contacts/bulk', { op: a.op, ids: a.ids, tag: a.tag });
    },
  },
  {
    name: 'contact_activity',
    title: 'Contact activity',
    description: 'One contact\'s campaign history, newest first: up to 50 events (sent, delivered, opened, clicked, bounced, complained …) each with its campaign name, plus when and how the contact was added. Transactional messages are not included; see list_messages.',
    inputSchema: { type: 'object', properties: { id: id('Contact id from list_contacts.') }, required: ['id'] },
    annotations: READ,
    requiredScopes: ['contacts.read'],
    handler: (call, a) => call('GET', '/contacts/' + encodeURIComponent(a.id) + '/activity'),
  },
  {
    name: 'wallet_balance',
    title: 'Wallet balance',
    description: 'Prepaid credit left, this month\'s usage, and how much of the free allowance remains.',
    inputSchema: NO_ARGS,
    annotations: READ,
    requiredScopes: ['wallet.read'],
    handler: (call) => call('GET', '/wallet/balance'),
  },
  {
    name: 'wallet_events',
    title: 'Wallet ledger',
    description: 'The prepaid-credit ledger, newest first: top-ups, send charges and refunds, each with amount_cents (in the account currency; wallet_balance names it), type, reason and time.',
    inputSchema: {
      type: 'object',
      properties: { limit: { type: 'integer', minimum: 1, maximum: 200, default: 50, description: 'How many entries, 1–200. Default 50.' } },
    },
    annotations: READ,
    requiredScopes: ['wallet.read'],
    handler: (call, a) => call('GET', '/wallet/events' + (a.limit ? '?limit=' + encodeURIComponent(a.limit) : '')),
  },
  {
    name: 'quote_cost',
    title: 'Quote send cost',
    description: 'What sending a given number of emails would cost right now, before sending: how many fall inside this month\'s free allowance, how many are billable, the price in cents of the account currency, and the current balance. It does not look at an audience; for a campaign, get the count from estimate_campaign first.',
    inputSchema: {
      type: 'object',
      properties: { count: { type: 'integer', minimum: 1, description: 'Number of emails to price.' } },
      required: ['count'],
    },
    annotations: READ,
    requiredScopes: ['wallet.read'],
    handler: (call, a) => call('POST', '/wallet/quote', { count: a.count }),
  },
  {
    name: 'get_me',
    title: 'Get account',
    description: 'The account this key belongs to: brand, plan, limits, usage — and key_mode ("test" keys record sends without delivering; "live" keys deliver).',
    inputSchema: NO_ARGS,
    annotations: READ,
    requiredScopes: ['account.read'],
    handler: (call) => call('GET', '/auth/me'),
  },
];

export const TOOL_BY_NAME = Object.fromEntries(TOOLS.map((t) => [t.name, t]));

// What a client sees in tools/list (and the server card): MCP field names only.
// requiredScopes and handler stay server-side.
export function publicTool(t) {
  return {
    name: t.name,
    title: t.title,
    description: t.description,
    inputSchema: t.inputSchema,
    annotations: { title: t.title, ...t.annotations },
  };
}

// Required arguments are checked before any network call, and reported as a
// tool error the model can read and correct (not a protocol error).
export function missingArgs(tool, args) {
  const a = args && typeof args === 'object' && !Array.isArray(args) ? args : {};
  return (tool.inputSchema.required || []).filter((k) => a[k] === undefined || a[k] === null || a[k] === '');
}

// What every MCP client is told at initialize. Tool descriptions are read
// per call; this is the one place to say something about the key itself.
export const SERVER_INSTRUCTIONS = [
  'MAAC Go Email: transactional email, campaigns and contacts for one account, authenticated by the API key in use.',
  'Keys come in two modes and the mode is in the prefix. sk_live_ keys deliver mail. sk_test_ keys only RECORD a message: send_email returns 202 with status "sent" and test_mode:true, but nothing reaches any inbox and nothing is charged.',
  'Before telling a user an email "was sent", check test_mode on the result (or call get_me and read key_mode). If it is a test key and they expect delivery, tell them to create an sk_live_ key at https://edm.cresclab.com/developers.',
  'For any email sent more than once, create_template once and then send_email with template_id + variables, rather than inlining HTML on every call.',
  'Test keys never deliver: send_email records the message without sending it, and send_campaign refuses a test key.',
  'For a campaign, run estimate_campaign before send_campaign and tell the user the recipient count. If a send is refused for credit, show the top-up link from the error.',
].join(' ');

export function toMcpToolResult(result) {
  let text = typeof result === 'string' ? result : JSON.stringify(result, null, 2);
  // A test-key send comes back "sent". Without this line every model read
  // that as delivered — the first outside tester did.
  if (result && typeof result === 'object' && result.test_mode === true && result.status) {
    text += '\n\nNOT DELIVERED: this API key is sk_test_, so the message was only recorded. No email reached ' + (result.to || 'the recipient') + ' and nothing was charged. To deliver for real, create an sk_live_ key at https://edm.cresclab.com/developers and use that instead.';
  }
  return { content: [{ type: 'text', text }] };
}

export function formatToolError(name, e) {
  const code = e?.data?.error || e?.message || 'error';
  const hint = {
    unauthorized: 'The API key is missing, revoked, or lacks the scope this tool needs.',
    insufficient_credit: 'The free allowance is used up and the prepaid wallet cannot cover this. Top up at https://edm.cresclab.com/settings#billing',
    daily_cap_exceeded: 'The daily send cap has been reached. It resets at midnight.',
    suppressed: 'That address unsubscribed, bounced or complained, so it cannot be mailed.',
    account_frozen: 'Sending is paused on this account.',
    template_not_found: 'No stored template has that id on this account. Call list_templates to see them, or create_template to make one.',
    template_name_taken: 'A template with that name already exists — use its id, or update_template.',
    too_many_templates: 'This account already holds 100 templates. Delete one first.',
    missing_body: 'Pass html or text, or a template_id.',
    missing_subject: 'Pass a subject, or a template_id whose template has one.',
    invalid_to: 'The `to` address is not a valid email address.',
    invalid_email: 'That is not a valid email address.',
    not_found: 'Nothing with that id on this account.',
    contact_limit: 'The plan\'s contact allowance is full. Upgrade in Settings → Billing at https://edm.cresclab.com/settings#billing',
    bad_op: 'op must be "tag" or "untag". This tool cannot delete contacts.',
    no_ids: 'Pass at least one contact id from list_contacts.',
    already_sent: 'This campaign has already been sent.',
    already_sending: 'This campaign is already sending.',
    approval_required: 'This workspace requires approval before a campaign is sent. Ask an admin to approve it in the editor.',
    no_recipients: 'The campaign\'s audience reaches nobody. Check it with estimate_campaign.',
    test_key_cannot_send_campaign: 'This is a test key (sk_test_…). Test keys never deliver, so they cannot send campaigns. Use a live key, or send it from the console.',
  }[code];
  // The rest of the error body (prices, limits, detail) is what lets the model
  // explain a refusal instead of guessing at it.
  const extra = e?.data && typeof e.data === 'object' ? Object.fromEntries(Object.entries(e.data).filter(([k]) => k !== 'error')) : {};
  return `${name} failed: ${code}${hint ? ' — ' + hint : ''}${Object.keys(extra).length ? '\n' + JSON.stringify(extra) : ''}`;
}
